### ISSUE TITLE
打包完运行获取不到config中的信息

### ISSUE THREAD

**Issue by yilovezy** [soundofautumn/dingdong-helper-console#2]
2022-04-26 16:46:07,536 [main] DEBUG [cn.hutool.setting.SettingLoader] - Load setting file [jar:file:/Users/yangbing/Documents/dingdong-helper-console/target/dingdong-helper-1.0.1-jar-with-dependencies.jar!/config.setting]
java.lang.IllegalArgumentException: InputStream is null !
	at cn.hutool.core.lang.Assert.lambda$notNull$3(Assert.java:213)
	at cn.hutool.core.lang.Assert.notNull(Assert.java:193)
	at cn.hutool.core.lang.Assert.notNull(Assert.java:213)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:149)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:135)
	at cn.hutool.core.io.IoUtil.copy(IoUtil.java:122)
	at cn.hutool.core.io.IoUtil.read(IoUtil.java:404)
	at cn.hutool.core.io.IoUtil.readBytes(IoUtil.java:491)
	at cn.hutool.core.io.IoUtil.readBytes(IoUtil.java:457)
	at cn.hutool.core.io.IoUtil.read(IoUtil.java:368)
	at com.helper.Api.sign(Api.java:58)
	at com.helper.Api.checkUserConfig(Api.java:130)
	at com.helper.Main.main(Main.java:61)
四月 26, 2022 4:46:07 下午 com.helper.Api checkUserConfig

**Comment by yilovezy** [comment]
少了一个斜杠，已自行解决
